version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    volumes:
      - /home/docker-volume/bitwarden/data:/data
    env_file:
      - /home/docker-volume/bitwarden/config.env
    ports:
      - "8880:80"
      - "3012:3012"
