version: "3"

services:
  photoview:
    image: rclone/rclone:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /home/docker-volume/.config/rclone:/config/rclone
      - /home/docker-volume/rclone/data:/data:shared
